### ISSUE TITLE
Set `padding_idx=0` by default in `nn.Embeddings`

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/metal#107]
By default `padding_idx` is set to `None`. Just based on how we do embedding mappings, this should be 0.

**Comment by bhancock8** [comment]
Snorkel MeTaL is moving into maintenance mode, as its features have been merged into Snorkel proper (https://github.com/snorkel-team/snorkel). As of Snorkel v0.9, abstains are represented with a -1, and we no longer natively support individual end model component modules, so I think we're safe to close this. Feel free to reopen if not. Thanks!
