### ISSUE TITLE
Unusually Long Training Time

### ISSUE THREAD

**Issue by danich1** [HazyResearch/metal#113]
I have a training set size of 2.7 M sentences each with variable length (I think the longest is 76 tokens) and am using this data set to training an LSTM network with attention. Using 4 GPUs, training one epoch takes up to ~36 hours. Is this normal? Is there a bottleneck somewhere in the code? Any feedback on this problem would be great. My hunch here is that there could be a lot of updating that has to happen during back-propagation, but I am interested to get your take on this abnormally long training time.
I also provided a screenshot to give more information on this: 

<img width="642" alt="screen shot 2018-12-12 at 2 38 31 pm" src="https://user-images.githubusercontent.com/3505417/49895083-94472f80-fe1d-11e8-8b1c-9cfe61c4bb7e.png">

**Comment by jdunnmon** [comment]
Hmm @danich1 what's the output of nvidia-smi -l 1 look like when you're training?  Am wondering if there's some bottleneck with the GPU.  Also, I notice the `DataParallel` call at the top.  How exactly are you doing that?  Am wondering if that is potentially a source of the issue...

**Comment by jdunnmon** [comment]
My immediate thoughts are as follows:

(1) we don't really handle multiple GPUs in a sophisticated way yet -- have you tried training a smaller version of your model on a single GPU to see if you see the same issue?
(2) Your compute utilization looks very small (5% max) -- that could imply an i/o bottleneck.  How are you loading your data?

**Comment by danich1** [comment]
(1) Will be testing that out today, when I get into the office. 

(2) I have about 2.6M data samples that contain integer tensors of variable lengths. Max length I think is ~100 tokens. This gets shipped into the LSTM's embedding layer for down stream calculations.

**Comment by danich1** [comment]
Update: I figured out the issue. I was feeding in sentences with a size of 961, which slows down the process significantly. Easy solution is for me to change some of my training data other wise would have to look into truncated back-propagation through time (TBPTT).

**Comment by ajratner** [comment]
@danich1 thanks so much for the great documentation on this issue!!
