### ISSUE TITLE
tqdm error in RandomSearchTuner

### ISSUE THREAD

**Issue by mlu355** [HazyResearch/metal#143]
The RandomSearchTuner throws the following error even when the "progress_bar" field is set to false.

Exception ignored in: <generator object tqdm_notebook.**iter** at 0x1a2e29d200>
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm_notebook.py", line 226, in **iter**
self.sp(bar_style='danger')
AttributeError: 'tqdm_notebook' object has no attribute 'sp'

Used LSTMModule wrapped in an EndModel. The bug can be recreated here: https://github.com/HazyResearch/hazy-icij-collab/tree/end_model
Error is in the jupyter notebook:
https://github.com/HazyResearch/hazy-icij-collab/blob/end_model/demo_code/maude_demo.ipynb

**Comment by bhancock8** [comment]
This isn't a tqdm error. This is just the error that tqdm adds to the stack trace when something else broke while the tqdm widget was active.
