### ISSUE TITLE
Startup problem - Basics.ipynb ( Need to know what I am missing)

### ISSUE THREAD

**Issue by rekhasinghal** [HazyResearch/metal#152]
I have followed the steps- path setting, conda environment setting. However it throws following error- seems module are missing- do I need to pip each of them independently.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-56c4f4548b46> in <module>()
      1 import sys
      2 sys.path.append('../../metal')
----> 3 import metal

~/metal/metal/__init__.py in <module>()
----> 1 from .end_model import EndModel
      2 from .label_model import LabelModel, MajorityClassVoter, MajorityLabelVoter, RandomVoter
      3 from .tuners import RandomSearchTuner
      4 
      5 __all__ = [

~/metal/metal/end_model/__init__.py in <module>()
----> 1 from .end_model import EndModel
      2 from .identity_module import IdentityModule
      3 from .logreg import LogisticRegression
      4 from .loss import SoftCrossEntropyLoss
      5 

~/metal/metal/end_model/end_model.py in <module>()
      3 import torch.nn.functional as F
      4 
----> 5 from metal.classifier import Classifier
      6 from metal.end_model.em_defaults import em_default_config
      7 from metal.end_model.identity_module import IdentityModule

~/metal/metal/classifier.py in <module>()
     11 
     12 from metal.analysis import confusion_matrix
---> 13 from metal.logging import Checkpointer, Logger, LogWriter, TensorBoardWriter
     14 from metal.metrics import metric_score
     15 from metal.utils import place_on_gpu, recursive_merge_dicts

~/metal/metal/logging/__init__.py in <module>()
      1 from .checkpointer import Checkpointer
      2 from .logger import Logger, Timer
----> 3 from .tensorboard import TensorBoardWriter
      4 from .writer import LogWriter
      5 

~/metal/metal/logging/tensorboard.py in <module>()
----> 1 from tensorboardX import SummaryWriter
      2 
      3 from metal.logging.writer import LogWriter
      4 
      5

**Comment by bhancock8** [comment]
I assume because you closed the issue that you were able to resolve it. Feel free to post your solution so that others can benefit as well.
