### ISSUE TITLE
Recommendation: Use logging rather than prints

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/metal#170]
As a python package, it would be more convenient if metal used `logging`, rather than just print statements. This way, code which imports metal can easily get metal output to the console or to a file by following standard logging practices. 

For example:

https://github.com/HazyResearch/metal/blob/bb085733ab1c8f046f76433b4322408ad4d56c90/metal/tuners/random_tuner.py#L76-L81

This is handy information, but I need to pipe stdout to a file or something to save it. If you use a logger instead, I can simply configure logging.

**Comment by henryre** [comment]
Active development is being moved to our main repo, https://github.com/snorkel-team/snorkel, which now uses logging for everything.
