### ISSUE TITLE
When is v0.5 being released ? Would it be significant refactor ?

### ISSUE THREAD

**Issue by shishircc** [HazyResearch/metal#172]
Due to GLUE leaderboard I stumbled upon this framework. This is really useful framework. 

I am planning to use it for my projects but I wonder whether I should wait for 0.5 to release first or I can start with 0.4 and later upgrade easily to 0.5 ?

**Comment by bhancock8** [comment]
Glad to hear you've got ideas for the framework! v0.4 does have support for MTL and there's a tutorial showing how to use it. But the upgrade to v0.5 is very significant; it was a total rewrite from scratch to make sure that there was complete decoupling of data/labels/models/metrics. We're still on track for v0.5 to be released by the end of this month, so another week or two tops. Stay tuned!

**Comment by vincentschen** [comment]
Hi @shishircc — we've brought the best of MeTaL into the latest v0.9 release of Snorkel! The `GenerativeModel` has been refactored into the [`LabelModel`](https://snorkel.readthedocs.io/en/master/packages/_autosummary/labeling/snorkel.labeling.LabelModel.html#snorkel.labeling.LabelModel) of Snorkel, which now supports multiclass labeling, and `EndModel` has been refactored into [`MultitaskClassifier`](https://snorkel.readthedocs.io/en/master/packages/_autosummary/classification/snorkel.classification.MultitaskClassifier.html).

We also have tutorials to reproduce our results in the application repo, https://github.com/HazyResearch/snorkel-superglue.

Check it out, and feel free to open any issues in the corresponding repositories if you have follow-up questions!
