### ISSUE TITLE
Bug in Metal.multitask.mt_end_model, line 114.

### ISSUE THREAD

**Issue by kexiao17** [HazyResearch/metal#177]
variable `output_dim` is used without being defined, the only definition of `output_dim` in this function is at line 101 inside another if statement.

**Comment by bhancock8** [comment]
Ah, you're right! Thanks for bringing this to our attention. With the release of v0.9 of Snorkel (https://github.com/snorkel-team/snorkel), we merged all the best features of MeTaL back into the main repository, including the multi-task end model (and many other major improvements; see https://www.snorkel.org/hello-world-v-0-9/ for details). Snorkel MeTaL is now in maintenance mode, but Snorkel proper is under active development with more support than ever. Take a look at the new `MultitaskClassifier` in Snorkel (tutorial here: https://www.snorkel.org/use-cases/multitask-tutorial) and let us know if you have any issues!

**Comment by bhancock8** [comment]
This should also be fixed now in MeTaL with the merge of PR #211.
