### ISSUE TITLE
Generative model snorkel vs Generative model metal

### ISSUE THREAD

**Issue by Wronskia** [HazyResearch/metal#179]
Hello,

Thank you for the great work. I was wondering what are the differences between the generative models of snorkel and metal. From my experiments, i noticed that metal gen model is a bit more unstable and much faster to train, is it expected behavior?

Also, using the dependency selector from snorkel to get dependencies doesn't seem to work with metal  (Singular matrix inversion error), do you have a function that can get us the dependencies in metal?

**Comment by ajratner** [comment]
Hi @Wronskia there are a number of differences (see resp. papers online), but at a high level:
- *Model:* By default, MeTaL uses a slightly more expressive model, where _conditional_ accuracy parameters are learned, i.e. an accuracy parameter for each (LF, class) pair; whereas the default model in Snorkel is just learning a single acc. param per LF
- *Speed:* MeTaL uses a new matrix completion-style approach which involves running e.g. SGD over a small matrix---which importantly does not scale wrt to the amount of unlabeled data---and thus is much faster; see recent AAAI-19 paper for details!

As to instability, not sure without seeing examples, but we'll look into it.

And regarding deps: In the current matrix completion-style approach, we require the set of dependencies to meet certain requirements (which guarantee that the resulting problem is uniquely solvable). My guess is that the deps from Snorkel's selection approach just don't necessarily uphold/check for this criterion; but we should at least create a better error message!  @paroma @fredsala

**Comment by Wronskia** [comment]
Hello @ajratner, 
Thanks a lot for your quick answer. Are you planning in a next release to provide a method that calculates automatically the dependencies? (I saw this TODO in the the train_model method of the gen model training)

In the meantime, what would you suggest to use to calculate the deps that meets your requirements in order to work with metal ?

Thanks

**Comment by vincentschen** [comment]
Hi @Wronskia — thanks for the question! I'll note that we've brought the best of MeTal to our v0.9 release of [Snorkel](https://github.com/snorkel-team/snorkel) — check it out!

We have Dependency Learning on our roadmap there; stay tuned for updates! (cc @paroma )
