### ISSUE TITLE
issue keras or Tensorflow in the future?

### ISSUE THREAD

**Issue by anjubaoGDUT** [HazyResearch/metal#196]
Is Metal a torch version only? Would you issue keras or Tensorflow in the future?

**Comment by bhancock8** [comment]
Hi @anjubaoGDUT, great question! And I have good news for you: The Snorkel MeTaL code is currently being merged into a major overhaul of the Snorkel project that will become Snorkel v0.9. It will include all your favorite parts of MeTaL, but with better documentation, unit tests, type checks, and more features. And it's on our roadmap to add Keras or Tensorflow support in that repo soon after its release. It will still probably be at least a month before that arrives, but it is on our queue. Stay tuned!
