### ISSUE TITLE
when applying metal, how to estimate noisy-label probability for multilabel problem of a single task

### ISSUE THREAD

**Issue by yyht** [HazyResearch/metal#198]

**Comment by vincentschen** [comment]
Hi @yyht — could you be more specific? What's the use-case/problem set-up?

**Comment by vincentschen** [comment]
Stale issue — closing for now. Please see Snorkel's implementation of the the `LabelModel`. If I'm understanding your question correctly, I believe [`get_weights`](https://snorkel.readthedocs.io/en/v0.9.0/packages/_autosummary/labeling/snorkel.labeling.LabelModel.html#snorkel.labeling.LabelModel.get_weights) should return label probabilities.
