### ISSUE TITLE
Keep track of changes as CHANGELOG

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/metal#199]
I'd be nice to keep track of changes as CHANGELOG.

Thanks,
Hiromu

**Comment by HiromuHota** [comment]
I found release notes in README (https://github.com/HazyResearch/metal#release-notes).
However, please consider to put these kinds of information into CHANGELOG.md as IMO it is the common practice.

**Comment by bhancock8** [comment]
Hi @HiromuHota, that's a great suggestion. The good news is that we're currently migrating MeTaL into a major revision of the main Snorkel project repo (v0.9 coming out at the end of July), and that repo is being written from the ground up with maintainability in mind. There will be automatic type checking, more comprehensive code coverage with unit tests, pip and conda installations, etc. And we'll also be more rigid about release schedules and documenting what changes between major and minor versions. Stay tuned! :)
