### ISSUE TITLE
How to use weak supervised learning with MMTL

### ISSUE THREAD

**Issue by yzj19870824** [HazyResearch/metal#203]
It's supervised learning In mmtl_basics.ipynb, how to use weak supervised learning with MMTL, just like multitask.ipynb  does?

**Comment by vincentschen** [comment]
Hi @yzj19870824 — great question. You're right, the tutorial mainly highlights the MMTL functionality in the modeling pipeline, but this framework is agnostic to the way that we create/build training sets.

I'll also note that the best of MeTaL has been refactored to the v0.9 release of [Snorkel](https://github.com/snorkel-team/snorkel) — please see the [repository of tutorials](https://github.com/snorkel-team/snorkel-tutorials) for examples of how weak supervision fits into the context of MMTL!
