### ISSUE TITLE
links to basic snorkel tutorials are broken. 

### ISSUE THREAD

**Issue by jennxf** [HazyResearch/metal#204]
**Correct path:** 
https://github.com/snorkel-team/snorkel-tutorials/blob/master/getting_started/getting_started.ipynb

**Old path:**
https://github.com/snorkel-team/snorkel/blob/master/tutorials/snark/Snark%20Tutorial.ipynb

**Comment by vincentschen** [comment]
Addressed! https://github.com/HazyResearch/metal/pull/205
