### ISSUE TITLE
How does an end model improve upon Snorkel?

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#206]
First of all, thank you for working on Snorkel, it's very cool. I've always had a question: if you're labeling your dataset based on the Snorkel model, and then train another model on purely that data, then how's the end model supposed to do better than Snorkel?

This is something that always puzzled me to be honest. Is it an empirical observation? Or is there a theoretical explanation?

In my experience, it seems like the end model smooths out the precision-recall curve and so it adds area.

Thanks

**Comment by bhancock8** [comment]
Duplicate question answered in Snorkel repo: https://github.com/snorkel-team/snorkel/issues/1431
