### ISSUE TITLE
Supporting "default" class

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#208]
Say you have a binary classification task. I've seen many use-cases in which the model should predict the negative by default unless an example hits a bunch of positive LFs.

However, if you only have positive LFs, then the Snorkel model seems to always predict positive. 

Have others run into this? Am I missing something?

One potential solution would be to add an LF for the default class that votes True for all examples so as to default the predictions towards the default class.

**Comment by brahmaneya** [comment]
Duplicate question answered in https://github.com/snorkel-team/snorkel/issues/1433
