### ISSUE TITLE
Question on LF influence on Snorkel predictions based on coverage

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#209]
I've observed that the more coverage a rule has, the more influence it has over the Snorkel model predictions. 

What would happen if you took all the LFs (assuming they're precise enough) and found their coverage. Then, gave them a vote weight proportional to their coverage?

I was thinking this could be another baseline to compare Snorkel against in addition to majority vote.

**Comment by bhancock8** [comment]
Duplicate question answered in Snorkel: https://github.com/snorkel-team/snorkel/issues/1434
