### ISSUE TITLE
Change LF stat "empirical accuracy" to "precision"

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#210]
I was using Metal's LF analysis function, which gives you the "empirical accuracy" of your LFs. It was pretty confusing, I wasn't sure if it was computing its accuracy or its precision. After some experimentation I realized it's computing rule precisions. So, I thought maybe it would be better to call it "precision" to avoid confusions.

**Comment by bhancock8** [comment]
Duplicate question answered in Snorkel repo: https://github.com/snorkel-team/snorkel/issues/1435
