### ISSUE TITLE
Parallelize ModelTuner.search() with dask

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/metal#23]
At least for RandomTuner, there's no reason evaluations of different configs need to be in series. We should be able to keep the single-threaded and multi-threaded versions very similar by wrapping the init/train/eval block in a method than can be parallelized using dask.delayed or dask.future.

**Comment by tridao** [comment]
Are you thinking of parallelizing using multiple CPU cores?
Shouldn't the model training (using Pytorch I assume) already saturate the CPU cores with MKL?

**Comment by bhancock8** [comment]
Hypothetically, yes? But I've observed that at least on our cluster, the CPUs aren't fully utilized when there's only one job running. This probably isn't a top priority though. I'll go ahead and close this for now.
