### ISSUE TITLE
cuda training support in classifier

### ISSUE THREAD

**Issue by cleemesser** [HazyResearch/metal#33]
Classifier in metal inherits from nn.Module and has its own internal _train() method. These work on the cpu but do not support cuda training as the Classifier.to(device) pattern from pytorch is ignored in the _train() code and the data is never sent to the gpu.

It looks like the _train code needs updating or other choices made to allow for clean cuda training

**Comment by ajratner** [comment]
Merged into master now (new release coming soon too!)
