### ISSUE TITLE
Reconstructing `LabelModel` object does not reset config in notebook

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/metal#37]
This is a pretty annoying and confusing silent failure mode... I guess the defaults config dict is overwritten somehow, and then loaded then upon class instantiation?  @bhancock8 any ideas?

**Comment by bhancock8** [comment]
Hmm, that's surprising, because when we load a model, the __init__ method isn't ever run. It just unpickles the object and you carry on your way (ideally). What do you mean by it does not reset config? Is config none, or is it just set to the default values?

**Comment by ajratner** [comment]
I mean that if I just create a new `LabelModel` (not load one), it doesn't seem to reset the default config dictionary, so I end up with the same configs that I had set in the previous `LabelModel` I was using- which is very unintuitive behavior.  It's because the defaults are loaded from another file as a separate object I suppose?

**Comment by bhancock8** [comment]
Just to leave a little more information here: the issue was that the imported default config was getting modified. We were copying it in recursive_merge_dicts, but not deep copying it.

**Comment by ajratner** [comment]
Awesome!  Want to push a patch to 0.1.6 :)?

**Comment by bhancock8** [comment]
Patched and updaed to 0.1.7 in 7eea4c2e42adf8b5d97a979376c65977fe244029.
