### ISSUE TITLE
LabelModel cannot load because no c_tree attribute

### ISSUE THREAD

**Issue by jdunnmon** [HazyResearch/metal#39]
When loading saved LabelModel, get the following error message:

''LabelModel' object has no attribute 'c_tree'' when trying to restore LabelModel from saved pickle.  This is fixed by running `train` before loading data, but results are not consistent with saved model.  Possibly related to #37.

**Comment by jdunnmon** [comment]
Update: manually pickling/unpickling to entire model object seems to fix this.  We could either add a simple utility to do this (like below) for users who aren't familiar, or just instruct users to pickle the model object.  This is currently working for me, and I get the same behavior upon reconstituting the model.

`def pickle_model(model, filename):
    with open(filename,'wb') as fl:
        pickle.dump(model,fl)
        
def unpickle_model(filename):
    with open(filename,'rb')as fl:
        model = pickle.load(fl)
    return model`

This way you also don't have to instantiate the model before loading it.

**Comment by ajratner** [comment]
@jdunnmon how is this different from what the `Classifier.save` function is already doing (it's not as far as I can see)?  In that function we're just pickling the whole `Classifier` object as well, exactly same as above. Could you provide more detail on what's going on here?  Thanks!

**Comment by bhancock8** [comment]
Can you see if this was fixed by the fix for #37?

**Comment by bhancock8** [comment]
Closing this for now. Reopen if you observe this behavior again.
