### ISSUE TITLE
Make MeTaL handle different numbers of candidates per task

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/metal#40]
From @SenWu

**Comment by astarostap** [comment]
Agree with this, if you could have a different training sets for each task (given all the training sets have the same features)  would be great.

**Comment by vincentschen** [comment]
Closing— latest version oft he MTL classifier implemented in [Snorkel Classification](https://snorkel.readthedocs.io/en/v0.9.0/packages/classification.html) package. Please open feature requests in the Snorkel repo if still applicable!
