### ISSUE TITLE
Improvements to lf_summary tool

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/metal#41]
From @SenWu 

- Add LF names instead of indices
- Add empirical accuracies

**Comment by ajratner** [comment]
@SenWu these seem to already be in the function, so closing for now!  You can include a list of LF names and these will replaces the indices; and you can pass in some labels Y to get empirical accuracies (can also pass in the learned accuracies too):

https://github.com/HazyResearch/metal/blob/f25849e121d32ac8152cb2bbb6ab11909eb81a82/metal/analysis.py#L141

**Comment by HiromuHota** [comment]
How can I get the learned (estimated) accuracies so that I can pass that as `est_accs`?
`LabelModel` used to have a member function `accs()` for that, but which was deleted at a7ae887547becc01818cefd25c72411b6e4aa44d.

**Comment by ajratner** [comment]
Hi @HiromuHota check out https://github.com/HazyResearch/metal/blob/9beb119d722e5b20176478a8fd61d3795b4c60e1/metal/label_model/label_model.py#L224

However, re-opening this issue as we should have `lf_summary` in as well!

**Comment by HiromuHota** [comment]
I had a hunch about it but was not really sure. Now it is clearer.
Thanks for re-opening it and assigned yourself to it.
Please let me know if you need any help in resolving it.

**Comment by vincentschen** [comment]
An update version of the `lf_summary` has been implemented as `LFAnalysis` in the snorkel repo. Please open an issue there with any suggestions!
