### ISSUE TITLE
Support customized weight for individual LF 

### ISSUE THREAD

**Issue by ljx1110** [HazyResearch/metal#44]
This is Jason from Ant Financial. We are using snorkel/metal in couple of our core risk management products. It's a rule-engine based system. To detect black samples, there are bunch of rules and models are used as label functions. Some of them are just blacklists of user id or IP address. They are known as "strong rule" and don't follow majority voting policy. We need force target label to be 1 if any strong rule (LF) is hit no matter how other LFs behave. In my talk with Alex this morning, there is an easy way to set it up in L2 regulation factor for this purpose. 

I appreciate if this can be done. Then we can customize the weight setting via interface. I'd like to issue a PR myself if instruction is given. Thanks!

**Comment by ajratner** [comment]
Thanks for posting! As discussed I’ll take care of today as it fits with
some other changes I’m merging in :)

**Comment by ljx1110** [comment]
Alex, have you got a chance to add the change? I saw "weight_decay" is added in optimizer now. This may be related to this issue. Could you please explain how to leverage the new added l2 reg to customize individual strong LF?

**Comment by ajratner** [comment]
Hey @ljx1110 I just merged in a change to master (about to push to pip as well) that should help here!  In particular, you can now pass two kwargs into the `LabelModel.train` method as _vectors_, with different values for each LF:
- `prec_init`
- `l2`

The first is your prior on the _precision_ (i.e. `P(Y=y | \lf_i = y)`) of each LF (set to 0.7 for all of them by default), and the second is the strength of the L2 regularization around this value.

Happy to discuss more about this later- let us know what you find!
