### ISSUE TITLE
Filter out uniform-probability data points coming in to EndModel

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/metal#46]
More generally, can weight by something here; but at least need to filter out "null" data points, e.g. ones that no LF fired for, when training `EndModel`.  Seems like this feature got lost in porting to the current codebase

**Comment by ajratner** [comment]
@jason-fries

**Comment by henryre** [comment]
Active development is being moved to our main repo, https://github.com/snorkel-team/snorkel, which now has utilities like https://snorkel.readthedocs.io/en/v0.9.0/packages/_autosummary/labeling/snorkel.labeling.filter_unlabeled_dataframe.html#snorkel.labeling.filter_unlabeled_dataframe to do exactly this.
