### ISSUE TITLE
Allow Different Label Functions Sizes for Multi-task learning

### ISSUE THREAD

**Issue by danich1** [HazyResearch/metal#52]
It would be nice if the multitask version supported differently label matrix sizes.  When I was using a list of three sparse matrices: `L[0]: (121, 34), L[1]: (121, 25) L[2]: (121, 25)`,  the MTLabelModel resulted in a broadcast error (shown below). Is this a bug? If not, is it easy to add this feature?
<img width="1017" alt="screen shot 2018-10-08 at 6 41 30 pm" src="https://user-images.githubusercontent.com/3505417/46637340-ca201d00-cb29-11e8-957b-0ef6ee3ea819.png">

**Comment by ajratner** [comment]
Hey @danich1 not a bug, but definitely a good feature to add easier / more graceful handling of this!

Currently, we assume that each labeling function (corresponding to columns of the matrices) labels each task- where it could just label 0 if it doesn't apply to a task.  So, for now, you would just zero-pad those label matrices.  I.e. for all three of your `L` matrices (corresponding to three tasks), each column should correspond to one labeling function- and may just contain all zeros for certain tasks.  Hope this helps, and if you think of nicer way to handle this automatically, happy to integrate!
