### ISSUE TITLE
Make sure all documentation and functions consistent re: 0 or 1-indexing

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/metal#65]
In the `LabelModel`, we have 0 reserved as special value for abstains; then in subsequent `EndModel` calls, we use 1 indexing to be internally consistent.  However we should do a cleaning pass to make sure that (a) this is consistent in documentation / checks / etc, and (b) doesn't trip up people just using the `EndModel` with non-probabilistic labels, who might expect 0-indexing.

**Comment by henryre** [comment]
Active development is being moved to our main repo, https://github.com/snorkel-team/snorkel, where we standardized -1 as abstain so that the label model and downstream classifiers can use the same non-abstain class indices.
