### ISSUE TITLE
Full pass on checking torch vs. np formats

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/metal#67]

**Comment by bhancock8** [comment]
Our purported strategy up to this point has been that we accept as input torch or numpy and immediately convert to torch. Internally, everything stays in torch. And then when we make predictions, we return them as numpy. The reasoning was that so many peoples' datasets are already in numpy and everyone is more familiar with numpy than torch, so if they want, they can use the whole library with just numpy inputs and outputs.

**Comment by henryre** [comment]
Active development is being moved to our main repo, https://github.com/snorkel-team/snorkel, where we've updated the interface to use NumPy as inputs/outputs and PyTorch internally.
