### ISSUE TITLE
potential bug in the multitask.TaskHierarchy?

### ISSUE THREAD

**Issue by tpeng** [HazyResearch/metal#72]
Hi,

I'm testing MeTal in multi task settings, and noticed the predicted labels from `predict_proba` seems wrong. i noticed the code at https://github.com/HazyResearch/metal/blob/master/metal/multitask/task_graph.py#L97 and L98 is bit suspicious, don't we need to sort the predecessors/successors? 

thanks,
--terry

**Comment by bhancock8** [comment]
Snorkel MeTaL is moving into maintenance mode, as its features have been merged into Snorkel proper (https://github.com/snorkel-team/snorkel). If this feature request still applies, feel free to repost there!
