### ISSUE TITLE
convert_labels accepts non-ints when it shouldn't

### ISSUE THREAD

**Issue by nishithbsk** [HazyResearch/metal#81]
[Function](https://github.com/HazyResearch/metal/blob/aa6d8461159042d7eecb9d1abfcbe09d1a6da666/metal/utils.py#L158) doesn't throw error when non-ints are passed in. Maybe add an assert?

**Comment by ajratner** [comment]
Agreed!

**Comment by brahmaneya** [comment]
Active development is being moved to our main repo, https://github.com/snorkel-team/snorkel, where we use the same labeling convention (-1 for abstain, 0...k-1 for actual labels) for both labeling functions and the end model, so we don't need a convert_labels function anymore.
