### ISSUE TITLE
On MTL models: Would be great to pick best model based on a metric / task pair

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#82]
In MTL you often have a target and an auxiliary task, and you actually care about how you're doing on your target task. So, as the model is training, it would be great if you could save the model that did best on the target task on a particular metric.

Currently it uses the mean amongst all tasks (for example, it will keep the model with the highest mean F1 across all tasks). What I'd like is to be able to pick the model with best F1 on a particular task

**Comment by ajratner** [comment]
Great call!  Yes in general we probably need to do a pass on the tuner and
checkpointer specifically with the MTL models in mind

**Comment by astarostap** [comment]
https://github.com/HazyResearch/metal/pull/86

**Comment by astarostap** [comment]
Done: https://github.com/HazyResearch/metal/pull/86
