### ISSUE TITLE
tensorboardX is not in the requirements-dev.txt file

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#84]
When importing "from metal.contrib.logging.tensorboard import TensorBoardWriter" I got an error saying that tensorboardX can't be found.

I checked the requirements.txt file is not there so I installed it via 'pip install tensorboardx'. I was wondering if there was a reason not to include it in requirements.txt or if it's a bug.

**Comment by jdunnmon** [comment]
@astarostap this is in the requirements file within the logging contrib directory -- the goal is to keep this with the contrib stuff and not cause dependency bloat for the entire repo.  

https://github.com/HazyResearch/metal/blob/master/metal/contrib/logging/requirements.txt

Closing this for now.
