### ISSUE TITLE
Enable saving best model to disk during training

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#88]
Would be great to be able to save the best models to disk during training in case the training fails or the Jupyter kernel dies at some point. That way you could load the model afterward and continue training without starting from scratch.

**Comment by ajratner** [comment]
Agreed!  Could add this to the `Checkpointer` class: https://github.com/HazyResearch/metal/blob/2ef583ce4196bcf16a21d4b6caa390ea51e0cc81/metal/utils.py#L36

And/or to the `Tuner` class.  Also see the Tuner/Logger code for some file naming / saving code that you can copy-paste to keep things standard!

**Comment by bhancock8** [comment]
Fixed by #109 and #134.
