### ISSUE TITLE
Enable giving more importance to the "target" task during training

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#89]
https://arxiv.org/pdf/1702.08303.pdf suggests in its conclusion that there are ways to give more importance to one task during training through a "non-uniform drawing of the task considered at each training iteration" or an "adaptation of the learning rates".

If that works that would be great in the case when you are trying to optimize performance on a specific task.

**Comment by ajratner** [comment]
Great idea!

To start, we could add in a simple task weighting scheme, which would go here:
https://github.com/HazyResearch/metal/blob/2ef583ce4196bcf16a21d4b6caa390ea51e0cc81/metal/multitask/mt_end_model.py#L309

But then yeah, trying out some of this stuff would be great!

**Comment by astarostap** [comment]
Yeah that looks like a good way to start!

**Comment by vincentschen** [comment]
Looks like this was addressed; feel free to re-open if still applicable!
