### ISSUE TITLE
Add multitask bi-LSTM model 

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#90]
Potential architecture is described in the "Model" section here: http://www.aclweb.org/anthology/E17-1005.

I think there's a PR for a normal bi-LSTM in the works by @nishithbsk , and when that's merged in we could potentially extend it to MTL?

**Comment by ajratner** [comment]
Yup once it's in, to start at least, it can just be fed in as the
`input_layer`

**Comment by astarostap** [comment]
Yup makes sense.

**Comment by bhancock8** [comment]
Snorkel MeTaL is moving into maintenance mode, as its features have been merged into Snorkel proper (https://github.com/snorkel-team/snorkel). If this feature request still applies, feel free to repost there!
