### ISSUE TITLE
Enable freezing MTL model & adding a new task

### ISSUE THREAD

**Issue by astarostap** [HazyResearch/metal#92]
From today's meeting. Adding it here to prioritize it accordingly.

**Comment by bhancock8** [comment]
The new `MultitaskClassifier` in Snorkel proper (https://github.com/snorkel-team/snorkel/) supports much more flexible ways of adding tasks to a multi-task model. As Snorkel MeTaL is now in maintenance mode and all active development is on Snorkel, closing this issue. Feel free to reopen on Snorkel repo if still applicable.
